#!/bin/bash
#SSShot

#Create screenshot of a user selection

if ${VERBOSE}
then
    echo -e "[RUNNING] Waiting for user to select an area...";
fi

mkdir -p ${SS_DIR}/${DATE}
import -silent ${SS_DIR}${DATE}/${IMG_ID}.png

if ${VERBOSE}
then
    echo -e "[${GREEN}OK${NC}] Selection screenshot taken.";
fi

if ${UPLOAD_ON_CAPTURE}
then
    if ${VERBOSE}
    then
        echo -e "[RUNNING] Uploading to remote server...";
    fi

    ssh "${SERVER}" "mkdir -p ${SERVER_DEST}${DATE}" && scp -r "${SS_DIR}${DATE}/${IMG_ID}.png" "${SERVER}:${SERVER_DEST}${DATE}"

    if ${VERBOSE}
    then
        echo -e "[${GREEN}OK${NC}] Uploading to remote server.";
    fi

    if ${COPY_CLIPBOARD}
    then
        echo ${SERVER_URL}${DATE}/${IMG_ID}.png | xclip -selection c
        
        if ${VERBOSE}
        then
            echo -e "[${GREEN}OK${NC}] Copy remote URL to clipboard.";
        fi
    fi
fi

if ${VERBOSE}
then
    echo -e "[${GREEN}OK${NC}] Done!";
fi

if ${SHOW_NOTIFICATIONS}
then
    notify-send ${PACKAGE} "User Selection Screenshot Complete!" -t 5000 -c "transfer.complete"
    echo $'\a'
fi